### ISSUE TITLE
Exception handling issue

### ISSUE THREAD

**Issue by Ankush-Chander** [citeproc-py/citeproc-py#125]
Hi,
Thanks for this awesome project.
 
I am getting following error in my code which is leading to entire formatting to fail.

```
Traceback (most recent call last):
  File "/work/packages/citeproc-py/citeproc/model.py", line 1463, in _is_uncertain_date
    circa = item.reference[date_variable].get('circa', False)
AttributeError: 'NoneType' object has no attribute 'get'
```

I tried following snippet and found that `AttributeError` is not getting caught as `VariableError`
```
class VariableError(Exception):
	pass
	
try:
	raise AttributeError("test")
except VariableError:
	print("caught VariableError")
except AttributeError:
	print("caught AttributeError")
except Exception:
	print("caught Exception")
>> caught AttributeError
```

I intend to  raise a pull request handling AttributeError [here](https://github.com/brechtm/citeproc-py/blob/cd5ff0c52fb00cb4b587d6ec45e7a4b6462e6582/citeproc/model.py#L1461) . Please suggest.

**Comment by tmorrell** [comment]
@Ankush-Chander can you confirm that this PR https://github.com/citeproc-py/citeproc-py/pull/89 fixes your issue? Or could you open a new PR with your error as a test case?

**Comment by Ankush-Chander** [comment]
Hi @tmorrell 
This fixes my issue. 
Thanks.

**Comment by tmorrell** [comment]
I've merged the fix. We're still working on release automation, so we don't yet know when the next release will be.
