### ISSUE TITLE
Is this package still maintained or actively developped?

### ISSUE THREAD

**Issue by dafrose** [citeproc-py/citeproc-py#88]
Hello @brechtm and thank you for developing and sharing this package.

I tried using it and ran into a couple of issues and soon realized that this package has not been active for 8 months, while new issues have been posted since then. Are you still planning to develop or maintain this package? If not, have other people taken it up (possibly elsewhere)? Can you recommend another similar project? (Note that I can totally understand, if you do not have time or are not willing to continue supporting this package.)

Best regards,
Daniel

**Comment by brechtm** [comment]
Hi Daniel. Unfortunately I do not have the time to maintain citeproc-py. I do have the intention to respond to issues, but I'm simply not getting to it.

The project would definitely benefit from having an active maintainer as a new release is long overdue and there are plenty of bugs left to be fixed. I would be glad to hand things over, but so far there have been no candidates. We could try reaching out to people that are actively using citeproc-py and see if they would like to take ownership.

As far as I know, there are not other functional citeproc implementations for Python.

**Comment by blackdwarf** [comment]
@brechtm I assume you would be open to reviewing PRs that fix issues and/or add new things? Not sure, of course, I will have time, but I may need a citeproc implementation in Python for some things, so figured it would be better to use something that is already out there and, of course, help if I can.

**Comment by Xunius** [comment]
I'm also looking for a python implementation for my python software. @blackdwarf are you using this code or have your found another one?

**Comment by blackdwarf** [comment]
@Xunius I tried to use it but it gave me some weird issues with the templates and because I was in a rush I just used the `citeproc-js` implementation. I need to take a look, though, and figure out what was wrong.

**Comment by Xunius** [comment]
@blackdwarf I see. Guess I'll have to learn some javascript.

**Comment by tmorrell** [comment]
This repo has now been migrated into an organizational repo, and there at least a few folks who can review PRs. More help is always appreciated though.
